create the add new user command when update-users takes a really long time to run
dimagi/commcare-cloud pull request #4302
Opened 2020-10-27 19:36 UTC by biyeun

`update-users` takes a really long time to run on environments like prod. this command can be used in combination with `update-user-key`

##### ENVIRONMENTS AFFECTED
prod

2020-10-27 20:25 UTC, calellowitz requested changes
I think this command is really confusing and only does a small part of what is necessary to set up a user. The new account will exist, but they wont be able to auth as either of the two users they should have access to (doesn't add their key), and even if they can get in, they won't be able to do much of what they should be allowed to because the sudoers file won't be updated.

I am not opposed to trying to make a command that limits the effect to one user in an effort to speed this up, but I think if it does, it should handle the complete process rather than only a small part and therefore leave the user in a bad state.

2020-10-27 20:48 UTC, knguyen142 commented on src/commcare_cloud/commands/ansible/ansible_playbook.py
> +    command = 'add-new-user'
nit, but can this be `update-user` or `add-user` to denote that it's running `update-users` on a select group. Semantically, `update-users` can also add new users, so removing `new` from it makes it simpler.

2020-10-27 21:08 UTC, biyeun commented
@calellowitz i think my goal here was to have this command work in tandem with `update-user-key` as far as the key updates go. `update-user-key` should be run after this. I was not aware of updating the sudoers file. I'll revisit this again tomorrow

2020-10-28 00:31 UTC, millerdev commented
> `update-user-key` should be run after this.

Rather than adding a whole new command, could we combine this with `update-user-key` and call it `update-user`?

2020-10-28 17:13 UTC, biyeun commented
@millerdev ok sounds good.

2020-10-28 18:01 UTC, biyeun commented
@calellowitz @knguyen142 @millerdev thanks for all your inputs! how does the current state of things look?

2020-10-28 18:05 UTC, calellowitz approved these changes
This looks much better! Thanks for incorporating all the feedback! Do you have a sense how long this takes to run?

2020-10-28 18:05 UTC, biyeun commented
@calellowitz on staging it took a minute

2020-10-28 18:06 UTC, calellowitz commented
> @calellowitz on staging it took a minute

Wow. That does sound nice.

2020-10-28 18:42 UTC, calellowitz requested changes
I should have caught this earlier, but this totally breaks the `sudoers` file. Since that template fills in allowed users by iterating over `dev_users`, this command replaces the allowed users with just the single user you are updating (plus `ansible` and `cchq`).

Relevant line https://github.com/dimagi/commcare-cloud/blob/master/src/commcare_cloud/ansible/roles/bootstrap-users/templates/sudoers.j2#L5

Current state of that line on staging `User_Alias HIPAA_USERS = ansible, matthewriley, cchq`

2020-10-28 19:18 UTC, millerdev reviewed
I like the combined/new command. However...

At risk of exposing my own hypocrisy (because I implemented `UpdateUserPublicKey`), I'm a little nervous about switching to a workflow where we rarely or never run `update-users` (because it takes forever). If someone forgets to run one of these commands on an environment when a given person leaves or whatever, that change would previously have been applied the next time `update-users` was run. A single-user workflow means we may never realize that something was forgotten.

If we are moving to a single-user workflow for performance reasons and as a side-effect losing some confidence that all machines can only be accessed by active users, maybe it also makes sense to introduce a regularly-scheduled user access audit?

2020-11-11 15:36 UTC, closed without merging