Add more doc and link to setting up releases
dimagi/commcare-cloud pull request #4374
Opened 2020-12-07 14:49 UTC by mkangia

Found myself a little lost trying to setup a private release on icds-staging the other day with specific branches.
So
1. Added an example in code itself for quick reference
2. Adding an example in the README for extensions
3. Added a link to README's relevant section in the common method called for both deploy and private releases, where i think it is relevant, though we might then need to rename the README title to "Manage releases" instead of "Private releases" if that makes sense?

##### ENVIRONMENTS AFFECTED

None

2020-12-08 08:07 UTC, snopoke requested changes

2020-12-08 08:07 UTC, snopoke commented on src/commcare_cloud/fab/README.md
> +For extensions, run:
```suggestion
The same can be applied to set the branch for any additional repositories that have been configured. Use the variable `<name>_code_branch` where `name` is the name given to the repository in `meta.yml`:
```

2020-12-08 08:07 UTC, snopoke commented on src/commcare_cloud/fab/README.md
> +cchq <env> fab setup_release --set <env>_code_branch=<Extension HQ BRANCH>
```suggestion
cchq <env> fab setup_release --set <NAME>_code_branch=<BRANCH NAME>
```

2020-12-08 12:11 UTC, snopoke approved these changes
Thanks!

2020-12-08 12:30 UTC, mkangia commented
Thanks @snopoke

2020-12-08 12:30 UTC, mkangia commented
Hey @dannyroberts 
Since Simon and I co-contributed to this, going to wait for a review from you as well. Feel free to merge it directly if all looks okay.

2020-12-21 15:02 UTC, dannyroberts approved these changes

2020-12-21 18:57 UTC, merged