Add content around migrating commcare apps only
dimagi/commcare-cloud pull request #6343
Opened 2024-07-11 15:06 UTC by Charl1996

https://dimagi.atlassian.net/browse/SC-3582

##### Environments Affected
Documentation change

2024-07-13 00:02 UTC, kaapstorm requested changes
Nice. Just a few nits.

2024-07-15 14:49 UTC, Charl1996 commented
English is hard

2024-07-16 13:54 UTC, kaapstorm approved these changes

2024-07-16 13:55 UTC, kaapstorm commented
English is ridiculous! :roll_eyes: :rofl:

2024-07-17 06:13 UTC, merged